version: '3'
services:
    unipi-students-api:
        image: konvoulgaris/unipi-students-api
        container_name: unipi-students-api
        restart: always
        ports:
        - 8080:8080
    unipi-notify:
        build: .
        container_name: unipi-notify
        restart: always
        depends_on:
        - unipi-students-api
