version: '3'
services:
    unipi-students-api:
        image: konvoulgaris/unipi-students-api
        container_name: unipi-students-api
        restart: always
        ports:
        - 8080:8080
    unipi-notify:
        build: .
        container_name: unipi-notify
        restart: always
        environment:
        - PATH_PREFIX=/usr/src/unipi-notify/
        - API_URL=unipi-students-api
        - REFRESH=30
        depends_on:
        - unipi-students-api
